import {layerFactory} from './util.js';

const LAYOUT_PROPERTIES = [
    {name: 'symbol-placement', defaultValue: 'point'},
    {name: 'symbol-spacing', defaultValue: 250},
    {name: 'symbol-avoid-edges', defaultValue: false},
    {name: 'symbol-sort-key'},
    {name: 'symbol-z-order', defaultValue: 'auto'},
    {name: 'icon-allow-overlap', defaultValue: false},
    {name: 'icon-ignore-placement', defaultValue: false},
    {name: 'icon-optional', defaultValue: false},
    {name: 'icon-rotation-alignment', defaultValue: 'auto'},
    {name: 'icon-size', defaultValue: 1},
    {name: 'icon-text-fit', defaultValue: 'none'},
    {name: 'icon-text-fit-padding', defaultValue: [0, 0, 0, 0]},
    {name: 'icon-image'},
    {name: 'icon-rotate', defaultValue: 0},
    {name: 'icon-padding', defaultValue: 2},
    {name: 'icon-keep-upright', defaultValue: false},
    {name: 'icon-offset', defaultValue: [0, 0]},
    {name: 'icon-anchor', defaultValue: 'center'},
    {name: 'icon-pitch-alignment', defaultValue: 'auto'},
    {name: 'text-pitch-alignment', defaultValue: 'auto'},
    {name: 'text-rotation-alignment', defaultValue: 'auto'},
    {name: 'text-field', defaultValue: ''},
    {name: 'text-font', defaultValue: ['Open Sans Regular', 'Arial Unicode MS Regular']},
    {name: 'text-size', defaultValue: 16},
    {name: 'text-max-width', defaultValue: 10},
    {name: 'text-line-height', defaultValue: 1.2},
    {name: 'text-letter-spacing', defaultValue: 0},
    {name: 'text-justify', defaultValue: 'center'},
    {name: 'text-radial-offset', defaultValue: 0},
    {name: 'text-variable-anchor'},
    {name: 'text-anchor', defaultValue: 'center'},
    {name: 'text-max-angle', defaultValue: 45},
    {name: 'text-writing-mode'},
    {name: 'text-rotate', defaultValue: 0},
    {name: 'text-padding', defaultValue: 2},
    {name: 'text-keep-upright', defaultValue: true},
    {name: 'text-transform', defaultValue: 'none'},
    {name: 'text-offset', defaultValue: [0, 0]},
    {name: 'text-allow-overlap', defaultValue: false},
    {name: 'text-ignore-placement', defaultValue: false},
    {name: 'text-optional', defaultValue: false},
    {name: 'visibility', defaultValue: 'visible'}
];

const PAINT_PROPERTIES = [
    {name: 'icon-opacity', defaultValue: 1},
    {name: 'icon-color', defaultValue: '#000000'},
    {name: 'icon-halo-color', defaultValue: 'rgba(0,0,0,0)'},
    {name: 'icon-halo-width', defaultValue: 0},
    {name: 'icon-halo-blur', defaultValue: 0},
    {name: 'icon-translate', defaultValue: [0, 0]},
    {name: 'icon-translate-anchor', defaultValue: 'map'},
    {name: 'text-opacity', defaultValue: 1},
    {name: 'text-color', defaultValue: '#000000'},
    {name: 'text-halo-color', defaultValue: 'rgba(0,0,0,0)'},
    {name: 'text-halo-width', defaultValue: 0},
    {name: 'text-halo-blur', defaultValue: 0},
    {name: 'text-translate', defaultValue: [0, 0]},
    {name: 'text-translate-anchor', defaultValue: 'map'}
];

export const SymbolLayer = layerFactory(LAYOUT_PROPERTIES, PAINT_PROPERTIES, 'symbol');
